###############################################################
# Program:
#     Checkpoint 05a, Getters and Setters
#     [instructor name obfuscated], CS165
# Author:
#     [student name obfuscated]
# Summary:
#     Summaries are not necessary for checkpoint assignments.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : money.h money.cpp check05a.cpp
	g++ money.cpp check05a.cpp

