#######################################################################
# Program:
#    Checkpoint 04b, more classes
#    [instructor name obfuscated], CS165
# Author:
#    [student name obfuscated]
# Summary: 
#    Summaries are not necessary for checkpoint assignments.
########################################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : date.h date.cpp check04b.cpp
	g++ date.cpp check04b.cpp
