###############################################################
# Program:
#     Checkpoint 11b, Class Templates
#     [instructor name obfuscated], CS165
# Author:
#     [student name obfuscated]
# Summary:
#     Summaries are not necessary for checkpoint assignments.
###############################################################


a.out : check11b.cpp pair.h
	g++ check11b.cpp
