###############################################################
# Program:
#     Assignment 04, Product inventory
#     [instructor name obfuscated], CS165
# Author:
#     [student name obfuscated]
# Summary:
#     Prompt the user for a product name, description, weight, and price.
#     Display user-specified info: advertising profile, line item, or receipt.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp
